### ISSUE TITLE
'Reduce' to 60 bytes?

### ISSUE THREAD

**Issue by ghost** [WebReflection/plain-tag#2]
(Drunken broken suggestions)

**Comment by WebReflection** [comment]
yeah, not only `arguments` is **not** an array, so you need `[].reduce.call(arguments, callback)` instead, but the performance would be crap, compared with the current function.

trust me, I've been golfing JS for 20 years, you can't beat in performance and size, the current implementation 👋

**Comment by WebReflection** [comment]
The Benchmark part is also what you should check:
https://github.com/WebReflection/plain-tag#benchmark

**Comment by WebReflection** [comment]
P.S. once IE11 will be abandoned, I'll also remove that `arguments.length` cache via `l` reference, so that'd be the smallest ever.

**Comment by ghost** [comment]
Oh yeah, thanks for directing me to the benchmark section, I completely ignored it somehow. Very interesting. This is (I think) the working version of what I posted, but the performance is indeed terrible. I learned something interesting...

```js
[...arguments].reduce((a, c, i) => i?a+c+t[i]:a, t[0]);
```
